### PR TITLE
WH01 and WM01 solutions

### PR DESCRIPTION
**Pull request by emsesc**
Completed WH01 (IP spoofing from localhost) and WM01 (javascript obfuscation, kind of forensics)

### CODE REVIEW

**Review by RealJammy — APPROVED** [review]
LGTM, thanks for the writeups!

**Review by RealJammy — CHANGES_REQUESTED** [review]
Sorry, could you remove the WM01 part of your writeup? @das-12  already did this

**Comment by emsesc** [comment]
@RealJammy No worries! Just removed 👍

**Review by RealJammy — APPROVED** [review]
LGTM!

**Pull request merged**
