### PR TITLE
added FM03

### PR DESCRIPTION
**Pull request by vgopi1**

### CODE REVIEW

**Review by RealJammy — CHANGES_REQUESTED** [review]
Is it possible to add some more detail?

**Comment by vgopi1** [comment]
> Is it possible to add some more detail?

I mean, there isn't much more to it, unless you want me to make this a brute-force tutorial. I can link to a hash cat tutorial if needed.

**Comment by emsesc** [comment]
Here's the command I used if it helps:
`sudo hashcat jwt.txt -m 16500 -a 3 -w 2 /usr/share/wordlists/rockyou.txt --force`

And the output you get:
```sh
Dirvolume:redwings
Session..........: hashcat
Status...........: Cracked
Hash.Type........: VeraCrypt PBKDF2-HMAC-SHA512 + XTS 1024 bit
Hash.Target......: dirvolume
Time.Started.....: Tue Apr  6 14:49:28 2021 (14 mins, 46 secs)
Time.Estimated...: Tue Apr  6 15:04:14 2021 (0 secs)
Guess.Base.......: File (/usr/share/wordlists/rockyou.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:        6 H/s (10.87ms) @ Accel:128 Loops:64 Thr:1 Vec:4
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 5120/14344385 (0.04%)
Rejected.........: 0/5120 (0.00%)
Restore.Point....: 4608/14344385 (0.03%)
```

**Comment by vgopi1** [comment]
> Here's the command I used if it helps:
> `sudo hashcat jwt.txt -m 16500 -a 3 -w 2 /usr/share/wordlists/rockyou.txt --force`
> 
> And the output you get:
> 
> ```shell
> Dirvolume:redwings
> Session..........: hashcat
> Status...........: Cracked
> Hash.Type........: VeraCrypt PBKDF2-HMAC-SHA512 + XTS 1024 bit
> Hash.Target......: dirvolume
> Time.Started.....: Tue Apr  6 14:49:28 2021 (14 mins, 46 secs)
> Time.Estimated...: Tue Apr  6 15:04:14 2021 (0 secs)
> Guess.Base.......: File (/usr/share/wordlists/rockyou.txt)
> Guess.Queue......: 1/1 (100.00%)
> Speed.#1.........:        6 H/s (10.87ms) @ Accel:128 Loops:64 Thr:1 Vec:4
> Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
> Progress.........: 5120/14344385 (0.04%)
> Rejected.........: 0/5120 (0.00%)
> Restore.Point....: 4608/14344385 (0.03%)
> ```

Thank you so much!

**Comment by vgopi1** [comment]
@RealJammy Changes made, please approve!

**Pull request closed without merging**
