### PR TITLE
Added FM03 with output

### PR DESCRIPTION
**Pull request by vgopi1**
Accidentally closed the previous PR.

### CODE REVIEW

**Review by RealJammy — APPROVED** [review]
LGTM, thanks for the PR

**Comment by emsesc** [comment]
@RealJammy @vgopi1 Sorry guys just realized I commented the wrong hashcat command - here's the correct one:

'sudo hashcat -a 0 -m 13722 dirvolume /usr/share/wordlists/rockyou.txt --force'

**Comment by RealJammy** [comment]
Don't worry, I'll just commit it straight in :)

**Comment by RealJammy** [comment]
https://github.com/Alic3C/Cyber-FastTrack-Spring-2021/commit/f799333dc5cbd6065829018e3638e4809bc56a4d

**Pull request merged**
