### PR TITLE
CH02 and WM03 writeups

### PR DESCRIPTION
**Pull request by emsesc**
Wrote solutions for CH02 (crib dragging) and WM03 (found a hash collision)

### CODE REVIEW

**Review by 404dcd — CHANGES_REQUESTED** [review]
Hi there - thanks for CH02! We already have a solution for WM03 though... would you mind uncommitting that one please?

**Comment by emsesc** [comment]
@404dcd done!

**Comment by 404dcd** [comment]
Looks good to me

**Review by 404dcd — APPROVED** [review]

**Review by RealJammy — APPROVED** [review]
Looks good to me! Thanks for the PR.

**Comment by 404dcd** [comment]
Yep, thanks for the PR

**Pull request merged**
